image: golang:1.13-alpine
stages:
  - build

variables:
  GITHUB_REPO: "github.com/Dadard29/go-api-net"

before_script:
  - apk add --update git
  - apk add gcc

build-and-test:
  stage: build
  script:
    - go get -v $GITHUB_REPO
    - cd src/$GITHUB_REPO
    - go test -v ./...